### ISSUE TITLE
Error in the pkg-config libdir variable (CMake)

### ISSUE THREAD

**Issue by vmagnin** [vmagnin/forcolormap#19]
After installing ForColormap in Ubuntu 23.04:
```bash
$ pkg-config --cflags --libs forcolormap
-I/usr/local/include -L/usr/local/usr/local/lib -lforcolormap 
```
The path `/usr/local/usr/local/lib` should be `/usr/local/lib` instead.

In the `install/template.pc` file we have:
```text
prefix = @CMAKE_INSTALL_PREFIX@
libdir = ${prefix}/@CMAKE_INSTALL_FULL_LIBDIR@
includedir = ${prefix}/@CMAKE_INSTALL_INCLUDEDIR@
...
Libs: -L${libdir} -l@PROJECT_NAME@
Cflags: -I${includedir}
```

We can write `libdir = ${prefix}/@CMAKE_INSTALL_LIBDIR@`
but we could also delete the `prefix` variable and use the `CMAKE_INSTALL_FULL_` version for both directories.
What solution should we use? @jchristopherson

https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html

**Comment by jchristopherson** [comment]
Hi @vmagnin, I'm open.  I personally am biased to using the prefix variable approach, but I really don't have a strong opinion one way or the other.

**Comment by vmagnin** [comment]
Thanks @jchristopherson 

same opinion:
> I personally am biased to using the prefix variable approach,

I have pushed the fix.

I have opened the same issue in forimage: https://github.com/gha3mi/forimage/issues/16

My objective is now to use forcolormap in a real simulation code. It is the best way to test it, evaluate the API, and the missing features.

**Comment by jchristopherson** [comment]
Thanks @vmagnin!
