### ISSUE TITLE
Using ForColormap as a shared library fails

### ISSUE THREAD

**Issue by vmagnin** [vmagnin/forcolormap#20]
@jchristopherson @gha3mi 

# The issue

I am trying to use ForColormap as a shared library (`.so` under Linux). I have written a `toy.f90` minimalist program:
```fortran
use forcolormap, only: Colormap, wp
type(Colormap) :: cmap

call cmap%set("cubehelix", 0.0_wp, 1.0_wp, 1024)
end
```
but the shared library `libforimage.so` is not found at runtime:
```bash
$ gfortran toy.f90 -Xlinker -rpath=/usr/local/lib $(pkg-config --cflags --libs forimage forcolormap)
$ ./a.out
./a.out: error while loading shared libraries: libforimage.so.0: cannot open shared object file: No such file or directory
```

# More information
System: Ubuntu 23.10
Compiler: GFortran 13.2.0

The `-Xlinker -rpath=/usr/local/lib` option allows the compiler to pass to the linker the runtime library search path.

The ForColormap project was built with the command `cmake -D BUILD_SHARED_LIBS=true ..`, then `make`, and installed in the system with:

```bash
$ sudo make install
[ 46%] Built target forimage
[100%] Built target forcolormap
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/libforimage.so.0.3.0
-- Installing: /usr/local/lib/libforimage.so.0
-- Installing: /usr/local/lib/libforimage.so
-- Up-to-date: /usr/local/include
-- Installing: /usr/local/include/lut.mod
-- Installing: /usr/local/include/pnm.mod
-- Installing: /usr/local/include/forimage_parameters.mod
-- Installing: /usr/local/include/forcolor.mod
-- Installing: /usr/local/include/forimage.mod
-- Installing: /usr/local/lib/cmake/forimage/forimageTargets.cmake
-- Installing: /usr/local/lib/cmake/forimage/forimageTargets-release.cmake
-- Installing: /usr/local/lib/cmake/forimage/forimageConfig.cmake
-- Installing: /usr/local/lib/cmake/forimage/forimageConfigVersion.cmake
-- Installing: /usr/local/lib/pkgconfig/forimage.pc
-- Installing: /usr/local/lib/libforcolormap.so.0.8.0
-- Installing: /usr/local/lib/libforcolormap.so.0
-- Set runtime path of "/usr/local/lib/libforcolormap.so.0.8.0" to ""
-- Installing: /usr/local/lib/libforcolormap.so
-- Up-to-date: /usr/local/include
-- Installing: /usr/local/include/miscellaneous_colormaps.mod
-- Installing: /usr/local/include/matplotlib_colormaps.mod
-- Installing: /usr/local/include/colormap_parameters.mod
-- Installing: /usr/local/include/forcolormap.mod
-- Installing: /usr/local/include/forcolormap_info.mod
-- Installing: /usr/local/include/scientific_colour_maps.mod
-- Installing: /usr/local/lib/cmake/forcolormap/forcolormapTargets.cmake
-- Installing: /usr/local/lib/cmake/forcolormap/forcolormapTargets-release.cmake
-- Installing: /usr/local/lib/cmake/forcolormap/forcolormapConfig.cmake
-- Installing: /usr/local/lib/cmake/forcolormap/forcolormapConfigVersion.cmake
-- Installing: /usr/local/lib/pkgconfig/forcolormap.pc
```
We can see that the `libforimage.so` and `libforcolormap.so` shared libraries are installed.

But we can notice a difference between ForImage and ForColormap, the following line is present only for ForColormap:
```bash
-- Set runtime path of "/usr/local/lib/libforcolormap.so.0.8.0" to ""
```

Files in the libraries directory:
```bash
$ ls -thor /usr/local/lib/libfor*
-rw-r--r-- 1 root 145K janv. 11 14:12 /usr/local/lib/libforimage.a
-rw-r--r-- 1 root 116K janv. 24 11:08 /usr/local/lib/libforimage.so.0.3.0
-rw-r--r-- 1 root 509K janv. 24 11:08 /usr/local/lib/libforcolormap.so.0.8.0
lrwxrwxrwx 1 root   20 janv. 24 11:08 /usr/local/lib/libforimage.so.0 -> libforimage.so.0.3.0
lrwxrwxrwx 1 root   16 janv. 24 11:08 /usr/local/lib/libforimage.so -> libforimage.so.0
lrwxrwxrwx 1 root   23 janv. 24 11:08 /usr/local/lib/libforcolormap.so.0 -> libforcolormap.so.0.8.0
lrwxrwxrwx 1 root   19 janv. 24 11:08 /usr/local/lib/libforcolormap.so -> libforcolormap.so.0
```

We can also see that the system knows the path to ForImage:
```bash
$ whereis libforimage.so.0
libforimage.so.0: /usr/local/lib/libforimage.so.0
```

But if we used the command ldd to print shared object dependencies:
```bash
$ ldd ./a.out
        linux-vdso.so.1 (0x00007ffc20faa000)
        libforcolormap.so.0 => /usr/local/lib/libforcolormap.so.0 (0x00007f4a2ef85000)
        libgfortran.so.5 => /lib/x86_64-linux-gnu/libgfortran.so.5 (0x00007f4a2ec00000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4a2eb15000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4a2ef37000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4a2e800000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4a2f006000)
        libforimage.so.0 => not found
```
we see that ForImage is not found.

```bash
$ pkg-config --cflags --libs forimage forcolormap
-I/usr/local/include -L/usr/local/lib -lforimage -lforcolormap 
```

**Comment by gha3mi** [comment]
I installed ForImage first, then ForColormap, and it works on my Ubuntu system. I am not a CMake expert, I will test it again without installing ForImage.

**Comment by gha3mi** [comment]
I manually cleaned up the installed library from `/usr/local...`, then I built and installed only ForColormap. It seems to be working on my system.

```shell
cd forcolormap
mkdir build && cd build
cmake -D BUILD_SHARED_LIBS=true ..
make
sudo make install
cd mytest
gfortran toy.f90 -Xlinker -rpath=/usr/local/lib $(pkg-config --cflags --libs forimage forcolormap)
./a.out  !  test
```

```shell
ldd ./a.out
linux-vdso.so.1 (0x00007f87abb88000)
libforimage.so.0 => /usr/local/lib/libforimage.so.0 (0x00007f87abb66000)
libforcolormap.so.0 => /usr/local/lib/libforcolormap.so.0 (0x00007f87abaea000)
libgfortran.so.5 => /prf/prg/lin/x86-x64/gcc/13.2.0/lib64/libgfortran.so.5 (0x00007f87ab813000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f87ab700000)
libgcc_s.so.1 => /prf/prg/lin/x86-x64/gcc/13.2.0/lib64/libgcc_s.so.1 (0x00007f87ab6db000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f87ab4b0000)
/lib64/ld-linux-x86-64.so.2 (0x00007f87abb8a000)
```

```fortran
program test

use forcolormap, only: Colormap, wp
type(Colormap) :: cmap

call cmap%set("cubehelix", 0.0_wp, 1.0_wp, 1024)

print*,'test'
end program test
```

[Edited:] I reinstalled it in another directory to ensure a clean installation.
`make install DESTDIR=...`
It appears to be functioning properly again on my system.

🤔

**Comment by vmagnin** [comment]
Thanks @gha3mi ! The good news is that my commands seem good...

I have once again tried to follow the same steps as you on another Ubuntu machine where I had never tried to install ForColormap or ForImage. I have also deleted the previous `forcolormap/build` directory to be sure everything is clean.
But I have still the same error message. And I don't understand why forimage is not found as all the needed `.so` files are visible in `/usr/local/lib`... It's the same on all my Ubuntu 23.10 machines.

I will now try also on my FreeBSD 14.0.

**Comment by jchristopherson** [comment]
Thanks @vmagnin and @gha3mi for your work.  I use a Windows machine and will see if I have similar troubles.

**Comment by vmagnin** [comment]
It works in FreeBSD 14.0 (no previous installation of ForColormap):
```bash
$ gfortran toy.f90 -Xlinker -rpath=/usr/local/lib $(PKG_CONFIG_PATH=/usr/local/lib/pkgconfig pkg-config --cflags --libs forimage forcolormap)
$ ./a.out
 test
```
(in that system I need to add `PKG_CONFIG_PATH=/usr/local/lib/pkgconfig` before the `pkg-config` system)

**Comment by vmagnin** [comment]
In FreeBSD 14.0, the versions are:
```bash
$ cmake --version
cmake version 3.28.1
$ gfortran --version
GNU Fortran (FreeBSD Ports Collection) 13.2.0
$ pkg-config --version
2.0.3
```
In Ubuntu 23.10, it is:
```bash
$ cmake --version
cmake version 3.27.4
$ gfortran --version
GNU Fortran (Ubuntu 13.2.0-4ubuntu3) 13.2.0
$ pkg-config --version
1.8.1
```

**Comment by gha3mi** [comment]
Good, that works!
I'm just curious about the version of pkg-config on your system. The current version on my Ubuntu 22.04.3 is:

```
pkg-config --version
0.29.2
```
I checked the latest tags on https://gitlab.freedesktop.org/pkg-config/pkg-config/-/tags, and it seems the latest version is from about 6 years ago, which is 0.29.0.

**Comment by vmagnin** [comment]
There are pkg-config and [pkgconf](https://github.com/pkgconf/pkgconf) ("Implementation of pkg-config without depending on GLib", according to Wikipedia).
Probably Ubuntu migrated toward pkgconf sometime between 22.04 and 23.10... I have only the 1.8.1 package in Synaptic (in fact two packages named pkgconf and pkg-config, but they seem the same).

**Comment by vmagnin** [comment]
I think I have found the problem. In my Ubuntu systems, I have:
```bash
$ echo $PKG_CONFIG_PATH
/opt/intel/oneapi/mpi/2021.11/lib/pkgconfig:/opt/intel/oneapi/compiler/2024.0/lib/pkgconfig
```
The `/usr/local/lib` has disappeared.

My problem is therefore fixed if I first type in my terminal:
```bash
$ export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
```
I will investigate in my `.bash_profile`, `.bashrc` and `/opt/intel/oneapi/setvars.sh` to see where it comes from...

Anyway, thanks @gha3mi and @jchristopherson for testing. It's important to do it in several systems.

**Comment by gha3mi** [comment]
Good that you found the problem!

Perhaps we could include those steps along with a simple test in the CI pipeline on Linux, macOS, and Windows to ensure compatibility checks.

**Comment by vmagnin** [comment]
I have added one line at the end of my `.bashrc` to update my environment variable:
```bash
# ifort :
source /opt/intel/oneapi/setvars.sh --force > /dev/null
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig/
```
Note also that the `-Xlinker` option seems then not necessary. You can just type:
```bash
$ gfortran toy.f90 $(pkg-config --cflags --libs forcolormap)
$ ./a.out
 test
```
Tomorrow I will update the README.md file with that command. And try to use ForColormap with my simulation.

**Comment by vmagnin** [comment]
On another Ubuntu machine, I wrestled with the same kind of problem, but the problem was in the LD_LIBRARY_PATH environment variable (used by the dynamic link loader `ld`). It was fixed with:
```bash
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
```
