### ISSUE TITLE
"bamako" scientific colormaps should not be in the Diverging category

### ISSUE THREAD

**Issue by vmagnin** [vmagnin/forcolormap#24]
The discrete versions of the "bamako" scientific colormaps have been put in the "Diverging" category:
https://github.com/gha3mi/forcolormap/tree/dev

but they should be in the "Sequential" category with the continuous version.

**Comment by vmagnin** [comment]
I have fixed this issue in src/colormaps_info.f90, but I guess @gha3mi you will have to regenerate https://github.com/gha3mi/forcolormap/tree/dev

**Comment by gha3mi** [comment]
Ok I will update it.

**Comment by gha3mi** [comment]
The colormaps list at https://github.com/gha3mi/forcolormap/tree/dev has been updated now.
