### ISSUE TITLE
Fix Broken Link to Cubehelix Colormap in README

### ISSUE THREAD

**Issue by gha3mi** [vmagnin/forcolormap#25]
The link to the cubehelix colormap in the README is broken. It currently points to https://www.mrao.cam.ac.uk/~dag/CUBEHELIX/.

**Comment by vmagnin** [comment]
The server is not down: https://www.mrao.cam.ac.uk/surveys/snrs/
but D.A. Green page is broken: https://www.mrao.cam.ac.uk/~dag/

**Comment by vmagnin** [comment]
It has migrated here: https://people.phy.cam.ac.uk/dag9/CUBEHELIX/
I will update the README.
