### ISSUE TITLE
Add check() Procedure

### ISSUE THREAD

**Issue by gha3mi** [vmagnin/forcolormap#26]
The `check()` procedure has been added to the `colormap_class`, as suggested by @vmagnin at https://github.com/vmagnin/forcolormap/tree/ali-dev. Tests have also been updated. @vmagnin, please test the validity of check().

**Comment by vmagnin** [comment]
Thanks Ali, 
all tests are OK:
```bash
[100%] Project compiled successfully.
Error 1: Colormap name 'actom10' not found! 'grayC' is set by default.
Error 2: Min value (zmin=2.0000) exceeds Max value (zmax=0.0000)! zmin and zmax are swapped.
Error 3: Number of Levels (levels=256) doesn't match colormap! Levels adjusted to colormap.
Error 2: Min value (zmin=2.0000) exceeds Max value (zmax=0.0000)! zmin and zmax are swapped.
```

**Comment by vmagnin** [comment]
When merging branches, a small conflict could arise in the README.md as I have updated the CUBEHELIX URL.

**Comment by gha3mi** [comment]
I'm trying to resolve it locally before submitting a pull request.
