### ISSUE TITLE
Colormap_info: Include all available colormaps

### ISSUE THREAD

**Issue by gha3mi** [vmagnin/forcolormap#28]

**Comment by vmagnin** [comment]
Add the missing colomaps:
- [x] "rainbow",
- [x] "inverted_rainbow",
- [x] "zebra",
- [x] "magma", 
- [x] "inferno",
- [x] "plasma", 
- [x] "viridis".

Then:
- [x] verify that no other is missing in Colormap_info.
- [x] Update the PDF guide.
