### ISSUE TITLE
Add Lagrange Interpolation function

### ISSUE THREAD

**Issue by gha3mi** [vmagnin/forcolormap#29]

**Comment by gha3mi** [comment]
@vmagnin
I have added a Lagrange interpolation function to the Colormap class in a branch. It is recommended to use it for lower orders (i.e., not many control colors) due to the presence of Runge's phenomenon.

**Comment by gha3mi** [comment]
I fixed a bug within the interpolation functions. Now, it ensures that the results are between 0 and 255.

Take a look at this example: I applied interpolation to the bam10 colormap (first colormap) to generate 256 levels using both Bezier (second colormap) and Lagrange (third colormap) methods. The original bam256 is displayed as the last one:

![bam10](https://github.com/vmagnin/forcolormap/assets/36126354/55b2a0dc-3e78-46dc-86a2-6c3af95e835a)
![custom_colorbar_bezier](https://github.com/vmagnin/forcolormap/assets/36126354/09d4d429-be04-4e13-98cf-dc60212e60a7)
![custom_colorbar_lagrange](https://github.com/vmagnin/forcolormap/assets/36126354/e3473c07-83c5-4bc6-9ab6-a2053fdc5c6f)
![bam](https://github.com/vmagnin/forcolormap/assets/36126354/c49dee2b-5fcf-44c4-a09d-84146a4c06af)

The results are not identical, and I did not expect them to be. Both interpolation functions are useful for creating custom colormaps rather than achieving exact matches.

**Comment by vmagnin** [comment]
> The results are not identical, and I did not expect them to be. Both interpolation functions are useful for creating custom colormaps rather than achieving exact matches.

Yes, very close, although by switching between two tabs I can see that in the last one the green is darker at the right extremity.

**Comment by gha3mi** [comment]
Maybe 10 colors are not sufficient. It might be more accurate if additional colors are employed.
