### ISSUE TITLE
Example: Create a `modify` example for the `shift()` method

### ISSUE THREAD

**Issue by gha3mi** [vmagnin/forcolormap#30]

**Comment by vmagnin** [comment]
The example will first demonstrate the `shift()` method, with concrete cases, e.g.:

- [x] the available cyclic colormaps have all their bright part in the middle. We can shift it to the extremities to obtain a cyclic colormap with the dark part in the middle, like certain diverging colormaps.
- [x] A categorical colormap can also be shifted if the user is not satisfied with the first colors.

Other files to update:

- [x] examples/README.md
- [x] examples/CMakeLists.txt
- [x] fpm.toml
- [x] README.md
- [x] CHANGELOG.md
- [x] ROADMAP.md
