### ISSUE TITLE
Add a finalizer method to Colormap type

### ISSUE THREAD

**Issue by gha3mi** [vmagnin/forcolormap#39]
Hi @vmagnin,

I am currently testing ForCAD with Valgrind to identify potential memory leaks. Since ForColormap is used as a dependency, I've discovered that it requires a finalizer procedure for memory cleanup, similar to the one below:

``` Fortran
pure subroutine finalize(self)
    class(Colormap), intent(inout) :: self
    if (allocated(self%map)) deallocate(self%map)
end subroutine
```

Would you agree to add it to the `Colormap` type?

**Comment by vmagnin** [comment]
Hi @gha3mi ,
of course. I suppose that it will be called automatically at the end of the program?

**Comment by gha3mi** [comment]
It's still unclear to me whether it is really necessary to use it. I posted the same question on the Fortran Discourse forum: https://fortran-lang.discourse.group/t/is-deallocation-needed-within-a-program/7973. This is the answer which states that it doesn't happen automatically:
https://fortran-lang.discourse.group/t/is-deallocation-needed-within-a-program/7973/3?u=ali

In my opinion, having the method is good, as the compiler does not clean up it automatically at the end of the program.

**Comment by vmagnin** [comment]
Done:
https://github.com/vmagnin/forcolormap/commit/756be0fb29a8784f3d6d4eb9d7776fb46df9aaa8
