### ISSUE TITLE
Suggestion: Define a New Module for Built-in Colormaps

### ISSUE THREAD

**Issue by gha3mi** [vmagnin/forcolormap#4]
Move the following colormaps as subroutines to a new module to organize all colormaps in separate modules:

- grey
- inverted_grey
- fire
- rainbow
- inverted_rainbow
- zebra
- cubehelix

**Comment by vmagnin** [comment]
Yes, that makes sense as the project has gained more scope than expected since I added the _Scientific Colour Maps..._
That could be a `miscellaneous` module for example.
