### ISSUE TITLE
Ideia for the logo

### ISSUE THREAD

**Issue by aslozada** [vmagnin/forcolormap#8]
The figure resembling a marble (_canica_ in spanish). The colors inside the marble can be chosen from the Scientific color maps.  If there is any interest, I can convert it to an SVG file. (fcm :wink:  fpm )

![fcm_ideia](https://github.com/vmagnin/forcolormap/assets/3170541/d30af627-1bc7-4f81-bb8a-6985dc8bc2d0)

**Comment by vmagnin** [comment]
Thanks Asdrubal for contributing,
yes, please propose a SVG!

**Comment by aslozada** [comment]
A first test with Crameri's roma (steps 8 and 12)
![logo_fcm_formats](https://github.com/vmagnin/forcolormap/assets/3170541/9a2d9fa6-1494-4e02-b100-fc59baad55c7)



![logo_fcm_roma_8](https://github.com/vmagnin/forcolormap/assets/3170541/3691d60b-a990-4605-9e45-6d1b05fce727)
![logo_fcm_roma_12](https://github.com/vmagnin/forcolormap/assets/3170541/777fae51-ac8d-4243-a863-43b7a7acb67a)

![logo_formats](https://github.com/vmagnin/forcolormap/assets/3170541/858d6b59-701b-451d-adeb-09f70eacb6bd)

**Comment by vmagnin** [comment]
Nice!
I prefer the first marble, with less different colors than the second one. And maybe the dark background.

I had the idea of using the Fortran purple, but I guess we could not obtain something pretty with it ...

**Comment by vmagnin** [comment]
Where did you get the roma font on his site?

**Comment by aslozada** [comment]
For the marble test, I obtained the RGB codes from this [link](https://observablehq.com/@nitaku/fabio-crameris-color-schemes), which contains a script (under the MIT license) for extracting color schemes from Crameri's color maps.

Of course, this was just for testing.

**Comment by gha3mi** [comment]
> For the marble test, I obtained the RGB codes from this [link](https://observablehq.com/@nitaku/fabio-crameris-color-schemes)

- [x] @vmagnin, we need to add the same _steps_ functionality from the mentioned link.

**Comment by vmagnin** [comment]
> @vmagnin, we need to add the same _steps_ functionality from the mentioned link.

Yes, it could be a method `extract(colormap_name, levels)`. I guess it could not be theoretically perfect for any number of levels (a question of modulo), but if we start from 256 levels and extract only typically ~<12, that won't be visible to the eye.

**Comment by aslozada** [comment]
> > For the marble test, I obtained the RGB codes from this [link](https://observablehq.com/@nitaku/fabio-crameris-color-schemes)
> 
> @vmagnin, we need to add the same _steps_ functionality from the mentioned link.

*An ideia for this funcionality*

According to CIE (International Commission on Illumination (http://cie.co.at/) ), to achieve a consistent perception, the CIE 1976 L*a*b* can be used.

A prototype function is: ∆E=√(∆L)^2+(∆a)^2+(∆b)^2

∆E: total color difference
∆a: difference in red-green component
∆b: difference in yellow-blue component
∆L: difference in lightness

To implement in the forcolormap, extracting from Crameri's scheme:
1. Convert RGB scheme to CIE 1976 L*a*b*
2. Use ∆E

**Comment by gha3mi** [comment]
Thanks, @aslozada! This could be useful. As I started programming, I found it to be very challenging. This could be helpful!

**Comment by aslozada** [comment]
> Thanks, @aslozada! This could be useful. As I started programming, I found it to be very challenging. This could be helpful!

An additional reference: convert from RGB to CIELab* requires two steps:
1. convert RGB to XYZ
2. convert XYZ to CIELab*
see [reference](http://www.brucelindbloom.com/index.html?Math.html)

....
Another issue:
In the initial [link](https://observablehq.com/@nitaku/fabio-crameris-color-schemes), when extracting color schemes, you need at least two steps. The first step corresponds to the first color in the color map, and the second step corresponds to the last color in the color map. In general, the code provided in that link involves a maximum of 100 steps. In all cases, the **first step uses the first color** in the Crameri's color map, and the **final step uses the last color** in the Crameri's color map. The selection of intermediate colors is based on a criterion to ensure a consistent perception of colors. (I haven't reviewed all the code, yet.)
Example:
![image](https://github.com/vmagnin/forcolormap/assets/3170541/1a6dddc2-c9d5-43ec-9b06-23a302f3315e)

**Comment by vmagnin** [comment]
> The selection of intermediate colors is based on a criterion to ensure a consistent perception of colors. (I haven't reviewed all the code, yet.)

One idea I had for discrete colormaps was to use https://en.wikipedia.org/wiki/Dyadic_rational
Well, it would work with 2, 3, 5, 9, 17... colors.

**Comment by gha3mi** [comment]
This is what I worked on last week:
original vanimo10:
![vanimo10](https://github.com/vmagnin/forcolormap/assets/36126354/18ca13e4-b46e-4a56-ad06-3cdfe2bc48e0)
my created vanimo10:
![my_vanimo10](https://github.com/vmagnin/forcolormap/assets/36126354/567a0b90-701a-4538-b9f5-28680bb0b310)
It's a bit hard for me to see, but there are small differences in the intermediate colors. We need to figure out the technique used for scientific colormaps to calculate interval sizes.

**Comment by vmagnin** [comment]
> It's a bit hard for me to see, but there are small differences in the intermediate colors. We need to figure out the technique used for scientific colormaps to calculate interval sizes.

My eyes can't see the difference... The way discrete colormaps are built seems not explained in the paper or the website. And I have not found the code used to do it, I don't know if and where it is available.

**Comment by aslozada** [comment]
After a bit more reading:

The technique used in this [link](https://observablehq.com/@xaquingv/fabio-crameris-color-schemes) to extract the discrete color schemes is derived from [ColorBrewer](https://colorbrewer2.org/#)(by Cynthia Brewer / [Repository](https://github.com/axismaps/colorbrewer/)). In summary, is a filter on a database. There isn´t a well-defined functional method for this task.

**Comment by gha3mi** [comment]
I implemented a subroutine that can perform extraction!

**Comment by vmagnin** [comment]
> For the marble test, I obtained the RGB codes from this [link](https://observablehq.com/@nitaku/fabio-crameris-color-schemes), which contains a script (under the MIT license) for extracting color schemes from Crameri's color maps.
> 
> Of course, this was just for testing.

Hi @aslozada 

- [x] we are starting again ForColormap development. Maybe you could make a PR with a `logo` directory containing SVG files with the logos you created?

**Comment by vmagnin** [comment]
@aslozada 
Which license do you prefer for your logo? A CC-BY-SA for example?

**Comment by aslozada** [comment]
> @aslozada 
> Which license do you prefer for your logo? A CC-BY-SA for example?

Yeah. The license CC-BY-SA is ok.

**Comment by vmagnin** [comment]
I have added the license. And put the logo at the head of the main README.md file.

**Comment by gha3mi** [comment]
The README with the logo looks great now!
